# Load and query the cleaned Telco CSV with MySQL

Install the project dependencies with `pip install -r requirements.txt`. This workflow uses SQLAlchemy with the PyMySQL driver. Create the target MySQL database before running the notebook (for example, `CREATE DATABASE apexplanet;`).

Copy the project-root `.env.example` to `.env` and set `DB_HOST`, `DB_PORT`, `DB_USER`, `DB_PASSWORD`, and `DB_NAME` there. `db_utils.py` loads `.env` when creating the engine; existing process environment variables take precedence. Never put credentials in this notebook or commit `.env`. The CSV loader defaults to `if_exists="fail"` and will not overwrite an existing table.

In [15]:
import sys
from pathlib import Path

from sqlalchemy import text

project_root = next(
    (path for path in (Path.cwd(), *Path.cwd().parents)
     if (path / "db_utils.py").is_file()),
    None,
)
if project_root is None:
    raise FileNotFoundError("Could not find db_utils.py in this directory or its parents.")
sys.path.insert(0, str(project_root))

from db_utils import create_mysql_engine, load_csv_to_mysql, read_sql_dataframe

csv_path = project_root / "data" / "processed" / "telco_churn_clean.csv"
engine = create_mysql_engine()

## Verify the MySQL connection

In [16]:
with engine.connect() as connection:
    mysql_version = connection.execute(text("SELECT VERSION()")).scalar_one()
print(f"Connected to MySQL {mysql_version}")

Connected to MySQL 8.0.46

## SQL fundamentals practice

The sample query above demonstrates `SELECT`, `WHERE`, `ORDER BY`, `LIMIT`, and bound parameters. The practice cell below adds joins, aggregates, subqueries, CTEs, and window functions. CTEs and window functions require MySQL 8.0 or later.

## Advanced SQL business questions

This Telco dataset is a single customer snapshot: it has no order dates or product sales. Monthly sales trends and product-category sales therefore cannot be calculated. The exercises use `monthly_charges` as a recurring-revenue snapshot, `total_charges` as lifetime billed charges, internet service as a service category, and churn status for retention.

In [18]:
query = """
SELECT customer_id, tenure, contract, monthly_charges, churn
FROM telco_churn
WHERE tenure >= :minimum_tenure
  AND churn = :churn_status
ORDER BY monthly_charges DESC
LIMIT :row_limit
"""
results = read_sql_dataframe(
    engine,
    query,
    params={"minimum_tenure": 12, "churn_status": "Yes", "row_limit": 10},
)
results

  customer_id  tenure        contract  monthly_charges churn
0  8199-ZLLSA      67        One year           118.35   Yes
1  2889-FPWRM      72        One year           117.80   Yes
2  2302-ANTDP      48  Month-to-month           117.45   Yes
3  9053-JZFKV      67        Two year           116.20   Yes
4  1444-VVSGW      70        One year           115.65   Yes
5  0201-OAMXR      70        One year           115.55   Yes
6  4361-BKAXE      41  Month-to-month           114.50   Yes
7  1555-DJEQW      70        Two year           114.20   Yes
8  9158-VCTQB      41  Month-to-month           113.60   Yes
9  7279-BUYWN      41  Month-to-month           113.20   Yes

In [21]:
from IPython.display import Markdown, display

sql_exercises = {
    "GROUP BY, HAVING, and aggregates": """
        SELECT contract,
               COUNT(*) AS customer_count,
               SUM(total_charges) AS lifetime_charges,
               AVG(monthly_charges) AS avg_monthly_charges,
               MIN(monthly_charges) AS min_monthly_charges,
               MAX(monthly_charges) AS max_monthly_charges,
               AVG(churn = 'Yes') AS churn_rate
        FROM telco_churn
        GROUP BY contract
        HAVING COUNT(*) >= 100
        ORDER BY lifetime_charges DESC
    """,
    "INNER JOIN: customers who churned": """
        WITH churned_customers AS (
            SELECT customer_id, churn
            FROM telco_churn
            WHERE churn = 'Yes'
        )
        SELECT t.customer_id, t.contract, c.churn
        FROM telco_churn AS t
        INNER JOIN churned_customers AS c ON c.customer_id = t.customer_id
        ORDER BY t.customer_id
        LIMIT 20
    """,
    "LEFT JOIN: all customers, with churn-cohort matches": """
        WITH churned_customers AS (
            SELECT customer_id, churn
            FROM telco_churn
            WHERE churn = 'Yes'
        )
        SELECT t.customer_id, t.contract, c.churn AS churn_cohort_match
        FROM telco_churn AS t
        LEFT JOIN churned_customers AS c ON c.customer_id = t.customer_id
        ORDER BY t.customer_id
        LIMIT 20
    """,
    "RIGHT JOIN: same result with the preserved table on the right": """
        WITH churned_customers AS (
            SELECT customer_id, churn
            FROM telco_churn
            WHERE churn = 'Yes'
        )
        SELECT t.customer_id, t.contract, c.churn AS churn_cohort_match
        FROM churned_customers AS c
        RIGHT JOIN telco_churn AS t ON t.customer_id = c.customer_id
        ORDER BY t.customer_id
        LIMIT 20
    """,
    "FULL OUTER JOIN emulation for MySQL using UNION ALL": """
        WITH churned_customers AS (
            SELECT customer_id, churn
            FROM telco_churn
            WHERE churn = 'Yes'
        )
        SELECT t.customer_id, t.contract, c.churn AS churn_cohort_match
        FROM telco_churn AS t
        LEFT JOIN churned_customers AS c ON c.customer_id = t.customer_id
        UNION ALL
        SELECT c.customer_id, NULL AS contract, c.churn AS churn_cohort_match
        FROM churned_customers AS c
        LEFT JOIN telco_churn AS t ON t.customer_id = c.customer_id
        WHERE t.customer_id IS NULL
        LIMIT 20
    """,
    "Subquery: customers billed above the overall average": """
        SELECT customer_id, contract, monthly_charges
        FROM telco_churn
        WHERE monthly_charges > (
            SELECT AVG(monthly_charges) FROM telco_churn
        )
        ORDER BY monthly_charges DESC
        LIMIT 10
    """,
    "CTE: retention rate by contract": """
        WITH contract_retention AS (
            SELECT contract,
                   COUNT(*) AS customer_count,
                   SUM(churn = 'No') AS retained_customers,
                   100.0 * SUM(churn = 'No') / COUNT(*) AS retention_rate_pct
            FROM telco_churn
            GROUP BY contract
        )
        SELECT *
        FROM contract_retention
        ORDER BY retention_rate_pct DESC
    """,
    "Window functions: ROW_NUMBER, RANK, LAG, and LEAD": """
        SELECT customer_id, contract, tenure, total_charges,
               ROW_NUMBER() OVER (
                   PARTITION BY contract ORDER BY total_charges DESC
               ) AS revenue_row_number,
               RANK() OVER (
                   PARTITION BY contract ORDER BY total_charges DESC
               ) AS revenue_rank,
               LAG(total_charges) OVER (
                   PARTITION BY contract ORDER BY tenure, customer_id
               ) AS previous_customer_charges,
               LEAD(total_charges) OVER (
                   PARTITION BY contract ORDER BY tenure, customer_id
               ) AS next_customer_charges
        FROM telco_churn
        ORDER BY contract, revenue_row_number
        LIMIT 20
    """,
    "Top 10 customers by lifetime billed charges (revenue proxy)": """
        SELECT customer_id, total_charges, tenure, contract
        FROM telco_churn
        ORDER BY total_charges DESC
        LIMIT 10
    """,
    "Service-category performance (revenue proxy and retention)": """
        SELECT internet_service AS service_category,
               COUNT(*) AS customer_count,
               SUM(total_charges) AS lifetime_charges,
               AVG(monthly_charges) AS avg_monthly_charges,
               100.0 * SUM(churn = 'No') / COUNT(*) AS retention_rate_pct
        FROM telco_churn
        GROUP BY internet_service
        ORDER BY lifetime_charges DESC
    """,
    "Current recurring-charge snapshot by contract (not a monthly trend)": """
        SELECT contract,
               SUM(monthly_charges) AS current_recurring_charges
        FROM telco_churn
        GROUP BY contract
        ORDER BY current_recurring_charges DESC
    """,
    "Five-tenure rolling average and cumulative customer count": """
        WITH tenure_summary AS (
            SELECT tenure,
                   COUNT(*) AS customer_count,
                   AVG(monthly_charges) AS avg_monthly_charges
            FROM telco_churn
            GROUP BY tenure
        )
        SELECT tenure, customer_count, avg_monthly_charges,
               AVG(avg_monthly_charges) OVER (
                   ORDER BY tenure ROWS BETWEEN 4 PRECEDING AND CURRENT ROW
               ) AS five_tenure_rolling_avg,
               SUM(customer_count) OVER (
                   ORDER BY tenure ROWS UNBOUNDED PRECEDING
               ) AS cumulative_customer_count
        FROM tenure_summary
        ORDER BY tenure
    """,
}

for exercise_name, exercise_query in sql_exercises.items():
    display(Markdown(f"### {exercise_name}"))
    display(read_sql_dataframe(engine, exercise_query))

### GROUP BY, HAVING, and aggregates

,contract,customer_count,lifetime_charges,avg_monthly_charges,min_monthly_charges,max_monthly_charges,churn_rate
0,Two year,1695,6297228.450,60.770413,18.40,118.75,0.0283
1,Month-to-month,3875,5305861.500,66.398490,18.75,117.45,0.4271
2,One year,1473,4468450.975,65.048608,18.25,118.60,0.1127

### INNER JOIN: customers who churned

   customer_id        contract churn
0   0004-TLHLJ  Month-to-month   Yes
1   0011-IGKFF  Month-to-month   Yes
2   0013-EXCHZ  Month-to-month   Yes
3   0022-TCJCI        One year   Yes
4   0023-HGHWL  Month-to-month   Yes
5   0023-XUOPT  Month-to-month   Yes
6   0031-PVLZI  Month-to-month   Yes
7   0032-PGELS  Month-to-month   Yes
8   0067-DKWBL  Month-to-month   Yes
9   0093-XWZFY  Month-to-month   Yes
10  0094-OIFMO  Month-to-month   Yes
11  0107-WESLM  Month-to-month   Yes
12  0107-YHINA  Month-to-month   Yes
13  0112-QWPNC        One year   Yes
14  0115-TFERT  Month-to-month   Yes
15  0117-LFRMW  Month-to-month   Yes
16  0122-OAHPZ  Month-to-month   Yes
17  0125-LZQXK  Month-to-month   Yes
18  0133-BMFZO  Month-to-month   Yes
19  0135-NMXAP  Month-to-month   Yes

### LEFT JOIN: all customers, with churn-cohort matches

   customer_id        contract churn_cohort_match
0   0002-ORFBO        One year               None
1   0003-MKNFE  Month-to-month               None
2   0004-TLHLJ  Month-to-month                Yes
3   0011-IGKFF  Month-to-month                Yes
4   0013-EXCHZ  Month-to-month                Yes
5   0013-MHZWF  Month-to-month               None
6   0013-SMEOE        Two year               None
7   0014-BMAQU        Two year               None
8   0015-UOCOJ  Month-to-month               None
9   0016-QLJIS        Two year               None
10  0017-DINOC        Two year               None
11  0017-IUDMW        Two year               None
12  0018-NYROU  Month-to-month               None
13  0019-EFAEP        Two year               None
14  0019-GFNTW        Two year               None
15  0020-INWCK        Two year               None
16  0020-JDNXP        One year               None
17  0021-IKXGC  Month-to-month               None
18  0022-TCJCI        One year                Yes
19  0023-HGHWL  Month-to-month                Yes

### RIGHT JOIN: same result with the preserved table on the right

   customer_id        contract churn_cohort_match
0   0002-ORFBO        One year               None
1   0003-MKNFE  Month-to-month               None
2   0004-TLHLJ  Month-to-month                Yes
3   0011-IGKFF  Month-to-month                Yes
4   0013-EXCHZ  Month-to-month                Yes
5   0013-MHZWF  Month-to-month               None
6   0013-SMEOE        Two year               None
7   0014-BMAQU        Two year               None
8   0015-UOCOJ  Month-to-month               None
9   0016-QLJIS        Two year               None
10  0017-DINOC        Two year               None
11  0017-IUDMW        Two year               None
12  0018-NYROU  Month-to-month               None
13  0019-EFAEP        Two year               None
14  0019-GFNTW        Two year               None
15  0020-INWCK        Two year               None
16  0020-JDNXP        One year               None
17  0021-IKXGC  Month-to-month               None
18  0022-TCJCI        One year                Yes
19  0023-HGHWL  Month-to-month                Yes

### FULL OUTER JOIN emulation for MySQL using UNION ALL

   customer_id        contract churn_cohort_match
0   7590-VHVEG  Month-to-month               None
1   5575-GNVDE        One year               None
2   3668-QPYBK  Month-to-month                Yes
3   7795-CFOCW        One year               None
4   9237-HQITU  Month-to-month                Yes
5   9305-CDSKC  Month-to-month                Yes
6   1452-KIOVK  Month-to-month               None
7   6713-OKOMC  Month-to-month               None
8   7892-POOKP  Month-to-month                Yes
9   6388-TABGU        One year               None
10  9763-GRSKD  Month-to-month               None
11  7469-LKBCI        Two year               None
12  8091-TTVAX        One year               None
13  0280-XJGEX  Month-to-month                Yes
14  5129-JLPIS  Month-to-month               None
15  3655-SNQYZ        Two year               None
16  8191-XWSZG        One year               None
17  9959-WOFKT        Two year               None
18  4190-MFLUW  Month-to-month                Yes
19  4183-MYFRB  Month-to-month               None

### Subquery: customers billed above the overall average

  customer_id        contract  monthly_charges
0  7569-NMZYQ        Two year           118.75
1  8984-HPEMB        Two year           118.65
2  5989-AXPUC        Two year           118.60
3  5734-EJKXG        One year           118.60
4  8199-ZLLSA        One year           118.35
5  9924-JPRMC        Two year           118.20
6  2889-FPWRM        One year           117.80
7  3810-DVDQQ        Two year           117.60
8  9739-JLPQJ        Two year           117.50
9  2302-ANTDP  Month-to-month           117.45

### CTE: retention rate by contract

         contract  customer_count  retained_customers  retention_rate_pct
0        Two year            1695              1647.0            97.16814
1        One year            1473              1307.0            88.73048
2  Month-to-month            3875              2220.0            57.29032

### Window functions: ROW_NUMBER, RANK, LAG, and LEAD

,customer_id,contract,tenure,total_charges,revenue_row_number,revenue_rank,previous_customer_charges,next_customer_charges
0,9481-IEBZY,Month-to-month,72,8061.50,1,1,6747.35,NaN
1,2615-YVMYX,Month-to-month,71,7713.55,2,2,7554.05,6951.15
2,5804-HYIEZ,Month-to-month,70,7554.05,3,3,6669.05,7713.55
3,5287-QWLKY,Month-to-month,71,7548.10,4,4,3765.05,6747.35
4,5502-RLUYV,Month-to-month,69,7446.90,5,5,5785.65,6382.00
5,7821-DPRQE,Month-to-month,68,7320.90,6,6,5589.30,3085.35
6,9090-SGQXL,Month-to-month,68,7299.65,7,7,3085.35,3687.75
7,9052-VKDUW,Month-to-month,65,7227.45,8,8,3673.15,6126.15
8,3838-OZURD,Month-to-month,66,7133.25,9,9,6595.00,4508.65
9,6710-HSJRD,Month-to-month,61,7132.15,10,10,6281.45,5500.60
10,8495-LJDFO,Month-to-month,64,7111.30,11,11,6548.65,4869.35
11,6067-NGCEU,Month-to-month,65,7107.00,12,12,6914.95,5931.00
12,4550-VBOFE,Month-to-month,70,7101.50,13,13,6470.10,6669.05
13,3761-FLYZI,Month-to-month,65,7082.45,14,14,6941.20,5688.45
14,7537-CBQUZ,Month-to-month,63,7031.45,15,15,6444.05,6215.35
15,0979-PHULV,Month-to-month,69,7007.60,16,16,3687.75,5869.40
16,1656-DRSMG,Month-to-month,63,7002.95,17,17,6603.00,6871.70
17,7207-RMRDB,Month-to-month,65,6985.65,18,18,5931.00,6496.15
18,2067-QYTCF,Month-to-month,64,6953.40,19,19,6081.40,5135.35
19,2674-MLXMN,Month-to-month,71,6951.15,20,20,7713.55,6669.45

### Top 10 customers by lifetime billed charges (revenue proxy)

  customer_id  total_charges  tenure  contract
0  2889-FPWRM        8684.80      72  One year
1  7569-NMZYQ        8672.45      72  Two year
2  9739-JLPQJ        8670.10      72  Two year
3  9788-HNGUT        8594.40      72  Two year
4  8879-XUAHX        8564.75      71  Two year
5  9924-JPRMC        8547.15      72  Two year
6  0675-NCDYU        8543.25      72  Two year
7  6650-BWFRT        8529.50      72  Two year
8  0164-APGRB        8496.70      72  Two year
9  1488-PBLJN        8477.70      72  Two year

### Service-category performance (revenue proxy and retention)

,service_category,customer_count,lifetime_charges,avg_monthly_charges,retention_rate_pct
0,Fiber optic,3096,9923622.950,91.500129,58.10724
1,DSL,2421,5128398.225,58.102169,81.04089
2,No,1526,1019519.750,21.079194,92.59502

### Current recurring-charge snapshot by contract (not a monthly trend)

         contract  current_recurring_charges
0  Month-to-month                  257294.15
1        Two year                  103005.85
2        One year                   95816.60

### Five-tenure rolling average and cumulative customer count

,tenure,customer_count,avg_monthly_charges,five_tenure_rolling_avg,cumulative_customer_count
0,0,11,41.418182,41.418182,11.0
1,1,613,50.485808,45.951995,624.0
2,2,238,57.206303,49.703431,862.0
3,3,200,58.015000,51.781323,1062.0
4,4,176,57.432670,52.911592,1238.0
...,...,...,...,...,...
68,68,100,73.321000,75.589464,6297.0
69,69,95,70.823158,74.597970,6392.0
70,70,119,76.378992,73.784163,6511.0
71,71,170,73.735588,73.318584,6681.0
72,72,362,80.695856,74.990919,7043.0

## Views and query optimization

Create a reusable contract summary view. `IF NOT EXISTS` makes the cell safe to re-run without replacing an existing view.

```sql
CREATE VIEW IF NOT EXISTS telco_contract_summary AS
SELECT contract, COUNT(*) AS customer_count,
       AVG(monthly_charges) AS avg_monthly_charges,
       100.0 * SUM(churn = 'No') / COUNT(*) AS retention_rate_pct
FROM telco_churn
GROUP BY contract;

SELECT * FROM telco_contract_summary;
EXPLAIN SELECT customer_id, monthly_charges
FROM telco_churn WHERE contract = 'One year' AND churn = 'No';
```

Use `EXPLAIN` before and after testing an index. For this filter, a candidate is `CREATE INDEX idx_telco_contract_churn ON telco_churn (contract, churn);` (run once only). Indexes add storage and write cost; keep an index only when the execution plan and workload justify it.

In [20]:
engine.dispose()